---
include:
  - board: seeeduino_xiao_ble
    shield: moNa2_R rgbled_adapter
    snippet: studio-rpc-usb-uart zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: moNa2_L rgbled_adapter
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset